#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/alsaperc
#     Description: Script for piping the alsa status into dzen
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

AMASTER=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $5}'`
ASTAT=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $6}'`
ICON=""

if [[ $ASTAT = "on" ]]; then
    ICON="spkr_01.xbm"
    PERCBAR=`echo -e "$AMASTER"\
        | gdbar -bg "#393939" -fg "#d6d6d6" -h 1 -w 60`
else
    ICON="spkr_02.xbm"
    PERCBAR=`echo 0\
        | gdbar -bg "#393939" -fg "#d6d6d6" -h 1 -w 60`
fi

ICON='^i(/home/epsi/.xmonad/assets/monitor/'"$ICON)"
echo "$ICON $PERCBAR"
