#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/pacshow
#     Description: Show the name of the packages awaiting the update
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------
background="#000000"
foreground=white
highlight="#308888"
FONT=profont-8
XPOS="920"
YPOS="19"
WIDTH="200"
pacmanlines=$(pacman -Qu | wc -l)
LINES=$(( $pacmanlines + 2 ))

updates=$(pacman -Qu)

(echo "^fg($highlight)Updates"; echo " ";echo "$updates") | dzen2 -p -fg $foreground -bg $background -fn $FONT -x $XPOS -y $YPOS -w $WIDTH -l $LINES -e 'enterslave=exit;leaveslave=exit;onstart=uncollapse,unhide;button1=exit;button3=exit'
